apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: kube-system
spec:
  provider: aws
  secretObjects:
  - secretName: k8s-secret
    type: Opaque
    data:
    - objectName: db_username
      key: admin
  parameters:     
    objects: | 
      - objectName: staging/admin
        objectType: secretsmanager
        jmesPath:
          - path: admin
            objectAlias: db_username 
