traefik:
  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true
      allowExternalNameServices: false
      namespaces: []
    # allow k8s ingress syntax for traefik routes
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      allowEmptyServices: true
      namespaces: []
      publishedService:
          enabled: true
  logs:
    general:
      level: DEBUG
    access:
      enable: true
  # https://www.revolgy.com/insights/blog/advanced-api-routing-in-eks-with-traefik-aws-loadbalancer-controller-and-external-dns
  # make a note that traefik does not work with ELB which comes from the service defintion. Keep responding with 404 all the time on https.
  # with current apporach ELB we can not have gRPC proxy, which means argocd cli won't woth with the url: https://argocd.staging.octolis.cloud
  # we create ingress in our charts/traefik that's why it's working
  service:
    enabled: true
    type: NodePort
  ports:
    traefik:
      expose: 
        default: true
      nodePort: 31587
      port: 8000
      exposedPort: 80
    web: 
      nodePort: 31588
      port: 8001
      expose: 
        default: true
      exposedPort: 8080
    websecure:
      port: 8443
      expose:
        default: true
      exposedPort: 443
      protocol: TCP
    metrics:
      port: 9100
      expose:
        default: true
      exposedPort: 9100
      protocol: TCP
  ingressRoute:
    dashboard:
      # -- Create an IngressRoute for the dashboard
      enabled: true