apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager   #specifies how to access and interact with the external APIs. In this example, it’s AWS Secrets Manager.
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secret
